<?php

$config['const_sisem_cajas']=array();

defined('ID_PARAMETRO_CAJA') OR define('ID_PARAMETRO_CAJA', 228);
defined('ID_TIPO_DOCUMENTO_RECIBO_INGRESO') OR define('ID_TIPO_DOCUMENTO_RECIBO_INGRESO', 81);
defined('ID_TIPO_DOCUMENTO_RECIBO_EGRESO') OR define('ID_TIPO_DOCUMENTO_RECIBO_EGRESO', 82);
defined('ID_TIPO_DOCUMENTO_VOUCHER_INGRESO') OR define('ID_TIPO_DOCUMENTO_VOUCHER_INGRESO', 83);
defined('ID_TIPO_DOCUMENTO_VOUCHER_EGRESO') OR define('ID_TIPO_DOCUMENTO_VOUCHER_EGRESO', 84);
defined('ID_TIPO_DOCUMENTO_TRANSFERENCIA_CAJA') OR define('ID_TIPO_DOCUMENTO_TRANSFERENCIA_CAJA', 85);
defined('ID_TIPO_DOCUMENTO_CANJE_LETRA_COBRAR') OR define('ID_TIPO_DOCUMENTO_CANJE_LETRA_COBRAR', 91);
defined('ID_TIPO_DOCUMENTO_PENDIENTE_LETRA_COBRAR') OR define('ID_TIPO_DOCUMENTO_PENDIENTE_LETRA_COBRAR', 91);
defined('INDICADOR_TIPO_COMPROBANTE_INGRESO') OR define('INDICADOR_TIPO_COMPROBANTE_INGRESO', 'I');
defined('INDICADOR_TIPO_COMPROBANTE_EGRESO') OR define('INDICADOR_TIPO_COMPROBANTE_EGRESO', 'S');
defined('INDICADOR_TIPO_COMPROBANTE_TRANSFERENCIA') OR define('INDICADOR_TIPO_COMPROBANTE_TRANSFERENCIA', 'T');

defined('ID_TIPO_OPERACION_CAJA_SALDO_INICIAL') OR define('ID_TIPO_OPERACION_CAJA_SALDO_INICIAL', 1);
defined('ID_TIPO_OPERACION_CAJA_VENTA_CONTADO') OR define('ID_TIPO_OPERACION_CAJA_VENTA_CONTADO', 2);
defined('ID_TIPO_OPERACION_CAJA_COMPRA_CONTADO') OR define('ID_TIPO_OPERACION_CAJA_COMPRA_CONTADO', 15);
defined('ID_TIPO_OPERACION_CAJA_EGRESO_NC_CLIENTE') OR define('ID_TIPO_OPERACION_CAJA_EGRESO_NC_CLIENTE', 18);
defined('ID_TIPO_OPERACION_CAJA_INGRESO_NC_PROVEEDOR') OR define('ID_TIPO_OPERACION_CAJA_INGRESO_NC_PROVEEDOR', 5);
defined('ID_TIPO_OPERACION_CAJA_COBRANZA_CLIENTE') OR define('ID_TIPO_OPERACION_CAJA_COBRANZA_CLIENTE', 3);
defined('ID_TIPO_OPERACION_CAJA_PAGO_PROVEEDOR') OR define('ID_TIPO_OPERACION_CAJA_PAGO_PROVEEDOR', 16);
defined('ID_TIPO_OPERACION_CAJA_TRANSFERENCIA_CAJA') OR define('ID_TIPO_OPERACION_CAJA_TRANSFERENCIA_CAJA', 58);
defined('ID_TIPO_OPERACION_CAJA_OTRO_INGRESO') OR define('ID_TIPO_OPERACION_CAJA_OTRO_INGRESO', 14); //POR DEFECTO EN CARGA INICIAL
defined('ID_TIPO_OPERACION_CAJA_OTRO_EGRESO') OR define('ID_TIPO_OPERACION_CAJA_OTRO_EGRESO', 57); //POR DEFECTO EN CARGA INICIAL

defined('INDICADOR_ESTADO_CAJA_PENDIENTE') OR define('INDICADOR_ESTADO_CAJA_PENDIENTE', 'O');
defined('INDICADOR_ESTADO_CAJA_CERRADO') OR define('INDICADOR_ESTADO_CAJA_CERRADO', 'C');

defined('ID_MEDIO_PAGO_EFECTIVO') OR define('ID_MEDIO_PAGO_EFECTIVO', 8);

defined('NUMERO_CAJA') OR define('NUMERO_CAJA',config_item("NUMERO_CAJA"));

defined('ID_PARAMETRO_CAJA_SALDO_NEGATIVO') OR define('ID_PARAMETRO_CAJA_SALDO_NEGATIVO', 290);

defined('NOMBRE_ARCHIVO_JASPER_DETALLADO_CUENTAS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_JASPER_DETALLADO_CUENTAS_POR_COBRAR',297); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DETALLADO_CUENTAS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_REPORTE_DETALLADO_CUENTAS_POR_COBRAR',298); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DOCUMENTOS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_JASPER_DOCUMENTOS_POR_COBRAR',299); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DOCUMENTOS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_REPORTE_DOCUMENTOS_POR_COBRAR',300); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MODELO_MOVIMIENTO_CUENTAS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_JASPER_MODELO_MOVIMIENTO_CUENTAS_POR_COBRAR',301); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MODELO_MOVIMIENTO_CUENTAS_POR_COBRAR')       OR define('NOMBRE_ARCHIVO_REPORTE_MODELO_MOVIMIENTO_CUENTAS_POR_COBRAR',302); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_CAJA')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_CAJA',303); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_CAJA')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_CAJA',304); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_SALDOS_POR_CLIENTES')       OR define('NOMBRE_ARCHIVO_JASPER_SALDOS_POR_CLIENTES',305); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_SALDOS_POR_CLIENTES')       OR define('NOMBRE_ARCHIVO_REPORTE_SALDOS_POR_CLIENTES',306); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DEUDAS_CLIENTE')       OR define('NOMBRE_ARCHIVO_JASPER_DEUDAS_CLIENTE',309); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DEUDAS_CLIENTE')       OR define('NOMBRE_ARCHIVO_REPORTE_DEUDAS_CLIENTE',310); //ParametroSistema

//REPORTES CAJA
defined('NOMBRE_ARCHIVO_JASPER_DEUDAS_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_JASPER_DEUDAS_PROVEEDOR',320); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DEUDAS_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_REPORTE_DEUDAS_PROVEEDOR',321); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DOCUMENTOS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_JASPER_DOCUMENTOS_POR_PAGAR',322); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DOCUMENTOS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_REPORTE_DOCUMENTOS_POR_PAGAR',323); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MODELO_MOVIMIENTO_CUENTAS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_JASPER_MODELO_MOVIMIENTO_CUENTAS_POR_PAGAR',324); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MODELO_MOVIMIENTO_CUENTAS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_REPORTE_MODELO_MOVIMIENTO_CUENTAS_POR_PAGAR',325); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DETALLADO_CUENTAS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_JASPER_DETALLADO_CUENTAS_POR_PAGAR',326); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DETALLADO_CUENTAS_POR_PAGAR')       OR define('NOMBRE_ARCHIVO_REPORTE_DETALLADO_CUENTAS_POR_PAGAR',327); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_SALDOS_POR_PROVEEDORES')       OR define('NOMBRE_ARCHIVO_JASPER_SALDOS_POR_PROVEEDORES',328); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_SALDOS_POR_PROVEEDORES')       OR define('NOMBRE_ARCHIVO_REPORTE_SALDOS_POR_PROVEEDORES',329); //ParametroSistema

defined('NOMBRE_ARCHIVO_JASPER_COBROS_POR_COBRADOR')       OR define('NOMBRE_ARCHIVO_JASPER_COBROS_POR_COBRADOR',355); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_COBROS_POR_COBRADOR')       OR define('NOMBRE_ARCHIVO_REPORTE_COBROS_POR_COBRADOR',356); //ParametroSistema

