<?php

$config['const_sisem_inventario']=array();

defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO',96); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO',95); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_FECHA_DETERMINADA',148); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_MARCA')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_MARCA',181); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_MARCA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_MARCA',180); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_MARCA_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_MARCA_FECHA_DETERMINADA',182); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_DUA')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_DUA',187); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DUA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DUA',186); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DUA_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DUA_FECHA_DETERMINADA',188); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_DOCUMENTO_ZOFRA')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_DOCUMENTO_ZOFRA',199); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DOCUMENTO_ZOFRA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DOCUMENTO_ZOFRA',198); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DOCUMENTO_ZOFRA_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_DOCUMENTO_ZOFRA_FECHA_DETERMINADA',200); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_DOCUMENTO_DUA')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_DOCUMENTO_DUA',190); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_DOCUMENTO_DUA')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_DOCUMENTO_DUA',189); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_DOCUMENTO_ZOFRA')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_DOCUMENTO_ZOFRA',202); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_DOCUMENTO_ZOFRA')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_DOCUMENTO_ZOFRA',201); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_STOCK_NEGATIVO')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_NEGATIVO',101); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_NEGATIVO')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_NEGATIVO',100); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN_VALORADO')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN_VALORADO',103); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN_VALORADO')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN_VALORADO',102); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN',135); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN',134); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN_DOCUMENTO_INGRESO')       OR define('NOMBRE_ARCHIVO_REPORTE_MOVIMIENTO_ALMACEN_DOCUMENTO_INGRESO',217); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN_DOCUMENTO_INGRESO')       OR define('NOMBRE_ARCHIVO_JASPER_MOVIMIENTO_ALMACEN_DOCUMENTO_INGRESO',216); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_DOCUMENTO_INGRESO')       OR define('NOMBRE_ARCHIVO_REPORTE_DOCUMENTO_INGRESO',213); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DOCUMENTO_INGRESO')       OR define('NOMBRE_ARCHIVO_JASPER_DOCUMENTO_INGRESO',212); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_INVENTARIO')       OR define('NOMBRE_ARCHIVO_REPORTE_INVENTARIO',219); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_INVENTARIO')       OR define('NOMBRE_ARCHIVO_JASPER_INVENTARIO',218); //ParametroSistema

defined('NOMBRE_PLANTILLA_EXCEL_INVENTARIO_INICIAL')       OR define('NOMBRE_PLANTILLA_EXCEL_INVENTARIO_INICIAL',146); //ParametroSistema

defined('ESTADO_PENDIENTE_NOTASALIDA') OR define('ESTADO_PENDIENTE_NOTASALIDA',1);
defined('ESTADO_PENDIENTE_NOTAENTRADA') OR define('ESTADO_PENDIENTE_NOTAENTRADA',2);

defined('ID_MOTIVO_NOTA_CREDITO_DESCUENTO_ITEM') OR define('ID_MOTIVO_NOTA_CREDITO_DESCUENTO_ITEM', 5);
defined('ID_MOTIVO_NOTA_SALIDA_VENTA_SIN_DOCUMENTO') OR define('ID_MOTIVO_NOTA_SALIDA_VENTA_SIN_DOCUMENTO', 40);

//RESTAURANT
defined('INTERVALO_TIEMPO_TARJETA_SIETE') OR define('INTERVALO_TIEMPO_TARJETA_SIETE', '1');

defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_LOTE')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_LOTE',345); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_LOTE')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_LOTE',344); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_LOTE_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_REPORTE_STOCK_PRODUCTO_LOTE_FECHA_DETERMINADA',347); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_LOTE_FECHA_DETERMINADA')       OR define('NOMBRE_ARCHIVO_JASPER_STOCK_PRODUCTO_LOTE_FECHA_DETERMINADA',346); //ParametroSistema

defined('ID_MOTIVO_INVENTARIO_INICIAL_SALDO_INICIAL') OR define('ID_MOTIVO_INVENTARIO_INICIAL_SALDO_INICIAL', 16);