<?php

$config['const_sisem_ventas_comprobantes_electronicos']=array();

defined('ESTADO_PENDIENTE_COMPROBANTE')       OR define('ESTADO_PENDIENTE_COMPROBANTE','P'); //PENDIENTE GENERAR
defined('ESTADO_GENERADO_COMPROBANTE')       OR define('ESTADO_GENERADO_COMPROBANTE','G'); //PENDIENTE DE ENVIAR
defined('ESTADO_ENVIADO_COMPROBANTE')       OR define('ESTADO_ENVIADO_COMPROBANTE','E'); //ENVIADO
defined('ESTADO_ANULADO_COMPROBANTE')       OR define('ESTADO_ANULADO_COMPROBANTE','N'); //GRUPO
defined('ESTADO_ELIMINADO_COMPROBANTE')       OR define('ESTADO_ELIMINADO_COMPROBANTE','X'); //GRUPO

defined('ESTADO_PW_PENDIENTE')       OR define('ESTADO_PW_PENDIENTE','D');
defined('ESTADO_PW_ENVIADO')       OR define('ESTADO_PW_ENVIADO','V');
defined('ESTADO_CPE_GENERADO')       OR define('ESTADO_CPE_GENERADO','G');
defined('ESTADO_CPE_ACEPTADO')       OR define('ESTADO_CPE_ACEPTADO','C');
defined('ESTADO_CPE_RECHAZADO')       OR define('ESTADO_CPE_RECHAZADO','R');
defined('ESTADO_CPE_EN_PROCESO')       OR define('ESTADO_CPE_EN_PROCESO','P');
defined('ESTADO_CPE_NINGUNO')       OR define('ESTADO_CPE_NINGUNO','');
defined('RUTA_CERTIFICADO_DIGITAL')       OR define('RUTA_CERTIFICADO_DIGITAL',111);
defined('ID_ESTADO_RESPUESTA_SUNAT_PROCESADO') OR define('ID_ESTADO_RESPUESTA_SUNAT_PROCESADO','1');
defined('ID_ESTADO_RESPUESTA_SUNAT_EN_PROCESO') OR define('ID_ESTADO_RESPUESTA_SUNAT_EN_PROCESO','2');
defined('ID_ESTADO_RESPUESTA_SUNAT_RECHAZADO') OR define('ID_ESTADO_RESPUESTA_SUNAT_RECHAZADO','3');

defined('ID_GRUPO_CARPETA_SUNAT')       OR define('ID_GRUPO_CARPETA_SUNAT',7);
defined('CODIGO_TIPO_DOCUMENTO_COMUNICACION_BAJA') OR define('CODIGO_TIPO_DOCUMENTO_COMUNICACION_BAJA','RA');
defined('CODIGO_TIPO_DOCUMENTO_RESUMEN_DIARIO') OR define('CODIGO_TIPO_DOCUMENTO_RESUMEN_DIARIO','RC');
defined('ID_GENERAR_ENVIAR_XML_SUNAT') OR define('ID_GENERAR_ENVIAR_XML_SUNAT',88);
defined('ID_RAIZ_FTP') OR define('ID_RAIZ_FTP',99);
defined('DELIMITADOR_CONTINGENCIA') or define('DELIMITADOR_CONTINGENCIA','|');
defined('TELEFONO_SUNAT') or define('TELEFONO_SUNAT','0-801-12-100');

defined('ESTADO_CPE_ANULADO') OR define('ESTADO_CPE_ANULADO','N');
defined('ESTADO_CPE_PENDIENTE_BAJA') OR define('ESTADO_CPE_PENDIENTE_BAJA','D');
defined('ESTADO_CPE_BAJA_GENERADA') OR define('ESTADO_CPE_BAJA_GENERADA','Q');
defined('ESTADO_CPE_BAJA_EN_PROCESO') OR define('ESTADO_CPE_BAJA_EN_PROCESO','Z');
defined('ESTADO_CPE_BAJA_ACEPTADA') OR define('ESTADO_CPE_BAJA_ACEPTADA','K');
defined('ESTADO_CPE_BAJA_RECHAZADA') OR define('ESTADO_CPE_BAJA_RECHAZADA','H');
defined('ESTADO_CPE_RESUMEN_DIARIO_GENERADO') OR define('ESTADO_CPE_RESUMEN_DIARIO_GENERADO','L');
defined('ESTADO_CPE_RESUMEN_DIARIO_EN_PROCESO') OR define('ESTADO_CPE_RESUMEN_DIARIO_EN_PROCESO','Y');
defined('ESTADO_CPE_RESUMEN_DIARIO_ACEPTADO') OR define('ESTADO_CPE_RESUMEN_DIARIO_ACEPTADO','O');
defined('ESTADO_CPE_RESUMEN_DIARIO_RECHAZADO') OR define('ESTADO_CPE_RESUMEN_DIARIO_RECHAZADO','U');

defined('CODIGO_SUNAT_ESTADO_ACEPTADO') OR define('CODIGO_SUNAT_ESTADO_ACEPTADO', 0);
defined('CODIGO_SUNAT_ESTADO_PENDIENTE') OR define('CODIGO_SUNAT_ESTADO_PENDIENTE', 98);
defined('CODIGO_SUNAT_ESTADO_RECHAZADO') OR define('CODIGO_SUNAT_ESTADO_RECHAZADO', 99);

defined('CODIGO_ERROR_CONECCION_SUNAT') OR define('CODIGO_ERROR_CONECCION_SUNAT', 0);
defined('CODIGO_ERROR_RECHAZO_SUNAT') OR define('CODIGO_ERROR_RECHAZO_SUNAT', 1);

defined('MOSTRAR_ENVIO_FACTURA_O_BOLETA') or define('MOSTRAR_ENVIO_FACTURA_O_BOLETA', 0); //0: PARA FACTURAS - 1: BOLETAS

defined('CODIGO_INICIO_ERROR_RECHAZO') or define('CODIGO_INICIO_ERROR_RECHAZO', 2000);
defined('CODIGO_FIN_ERROR_RECHAZO') or define('CODIGO_FIN_ERROR_RECHAZO', 3999); 

defined('ID_PARAMETRO_SISTEMA_BETA_SUNAT') or define('ID_PARAMETRO_SISTEMA_BETA_SUNAT', 150); 
defined('ID_PARAMETRO_SIETE_DIAS_SUNAT') or define('ID_PARAMETRO_SIETE_DIAS_SUNAT', 276); 

defined('ID_URL_WSDL_SUNAT') OR define('ID_URL_WSDL_SUNAT', 150);
defined('ID_URL_WSDL_OSE') OR define('ID_URL_WSDL_OSE', 307);

//RUTAS SUNAT
defined('URL_ENVIO_SUNAT_BETA') OR define('URL_ENVIO_SUNAT_BETA', 'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl');
// defined('URL_ENVIO_SUNAT_PRODUCCION') OR define('URL_ENVIO_SUNAT_PRODUCCION', 'https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl');
defined('URL_ENVIO_SUNAT_PRODUCCION') OR define('URL_ENVIO_SUNAT_PRODUCCION', APP_PATH_URL."assets/plantillas/billService.xml?wsdl");

defined('URL_ENVIO_SUNAT_GUIA_BETA') OR define('URL_ENVIO_SUNAT_GUIA_BETA', 'https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService?wsdl');
defined('URL_ENVIO_SUNAT_GUIA_PRODUCCION') OR define('URL_ENVIO_SUNAT_GUIA_PRODUCCION', 'https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService?wsdl');

//RUTAS OSE
defined('URL_ENVIO_OSE_BETA') OR define('URL_ENVIO_OSE_BETA', 'https://demo-ose.nubefact.com/ol-ti-itcpe/billService?wsdl');
defined('URL_ENVIO_OSE_PRODUCCION') OR define('URL_ENVIO_OSE_PRODUCCION', "https://ose.nubefact.com/ol-ti-itcpe/billService?wsdl");

defined('URL_ENVIO_OSE_GUIA_BETA') OR define('URL_ENVIO_OSE_GUIA_BETA', 'https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService?wsdl');
defined('URL_ENVIO_OSE_GUIA_PRODUCCION') OR define('URL_ENVIO_OSE_GUIA_PRODUCCION', 'https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService?wsdl');

defined('NUMERO_COMPROBANTES_MAXIMO_RESUMEN_DIARIO') OR define('NUMERO_COMPROBANTES_MAXIMO_RESUMEN_DIARIO', 500);
defined('ID_PARAMETRO_CARPETA_URL_CPE') OR define('ID_PARAMETRO_CARPETA_URL_CPE', 361);
//R23.01 - PLAZO DE DIAS PARA EL ENVIO A LA SUNAT
defined('PLAZO_DE_DIAS_SUNAT') OR define('PLAZO_DE_DIAS_SUNAT', 3);
