<?php

$config['const_sisem_compras']=array();

defined('NOMBRE_ARCHIVO_REPORTE_DETALLADO_COMPRA')       OR define('NOMBRE_ARCHIVO_REPORTE_DETALLADO_COMPRA',123); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DETALLADO_COMPRA')       OR define('NOMBRE_ARCHIVO_JASPER_DETALLADO_COMPRA',124); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_GENERAL_COMPRA')       OR define('NOMBRE_ARCHIVO_REPORTE_GENERAL_COMPRA',125); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GENERAL_COMPRA')       OR define('NOMBRE_ARCHIVO_JASPER_GENERAL_COMPRA',126); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_PRODUCTO_MAS_COMPRADO')       OR define('NOMBRE_ARCHIVO_REPORTE_PRODUCTO_MAS_COMPRADO',128); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_PRODUCTO_MAS_COMPRADO')       OR define('NOMBRE_ARCHIVO_JASPER_PRODUCTO_MAS_COMPRADO',129); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_COMPRAS_MENSUALES')       OR define('NOMBRE_ARCHIVO_REPORTE_COMPRAS_MENSUALES',130); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_COMPRAS_MENSUALES')       OR define('NOMBRE_ARCHIVO_JASPER_COMPRAS_MENSUALES',131); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_COMPRAS_POR_MERCADERIA')       OR define('NOMBRE_ARCHIVO_REPORTE_COMPRAS_POR_MERCADERIAS',145); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_COMPRAS_POR_MERCADERIA')       OR define('NOMBRE_ARCHIVO_JASPER_COMPRAS_POR_MERCADERIA',144); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_CODIGO_PRODUCTO_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_REPORTE_CODIGO_PRODUCTO_PROVEEDOR',161); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_CODIGO_PRODUCTO_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_JASPER_CODIGO_PRODUCTO_PROVEEDOR',160); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_SALDO_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_REPORTE_SALDO_PROVEEDOR',208); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_SALDO_PROVEEDOR')       OR define('NOMBRE_ARCHIVO_JASPER_SALDO_PROVEEDOR',207); //ParametroSistema
defined('ID_CODIGO_PRODUCTO_PROVEEDOR')       OR define('ID_CODIGO_PRODUCTO_PROVEEDOR',159);

defined('ID_NUM_POR_PAGINA_COMPROBANTECOMPRA')       OR define('ID_NUM_POR_PAGINA_COMPROBANTECOMPRA',77);
defined('ID_MOTIVO_NOTA_SALIDA_DEVOLUCION_PROVEEDOR_CON_DOCUMENTO') OR define('ID_MOTIVO_NOTA_SALIDA_DEVOLUCION_PROVEEDOR_CON_DOCUMENTO',25);

defined('ID_MOTIVO_NOTA_ENTRADA_COMPRA_CON_DOCUMENTO') OR define('ID_MOTIVO_NOTA_ENTRADA_COMPRA_CON_DOCUMENTO',2);

defined('ID_TIPOCOMPRA_MERCADERIA') OR define('ID_TIPOCOMPRA_MERCADERIA',1);
defined('ID_TIPOCOMPRA_GASTO') OR define('ID_TIPOCOMPRA_GASTO',2);
defined('ID_TIPOCOMPRA_COSTOAGREGADO') OR define('ID_TIPOCOMPRA_COSTOAGREGADO',3);

//MOTIVOS DE NOTAS
defined('ID_MOTIVO_NOTA_DEBITO_AUMENTO_VALOR') OR define('ID_MOTIVO_NOTA_DEBITO_AUMENTO_VALOR',2);
defined('ID_PARAMETRO_TAMANO_SERIE_COMPRA') OR define('ID_PARAMETRO_TAMANO_SERIE_COMPRA',226);
defined('ID_PARAMETRO_PRECIO_COMPRA') OR define('ID_PARAMETRO_PRECIO_COMPRA',234);
defined('ID_PARAMETRO_PRODUCTO_DUPLICADO') OR define('ID_PARAMETRO_PRODUCTO_DUPLICADO',265);

defined('ID_PARAMETRO_TIPO_DOCUMENTO_DUA_ALTERNATIVO') OR define('ID_PARAMETRO_TIPO_DOCUMENTO_DUA_ALTERNATIVO',311);

defined('NOMBRE_ARCHIVO_REPORTE_REGISTRO_COMPRA_8_1')      OR define('NOMBRE_ARCHIVO_REPORTE_REGISTRO_COMPRA_8_1',349); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_REGISTRO_COMPRA_8_1')       OR define('NOMBRE_ARCHIVO_JASPER_REGISTRO_COMPRA_8_1',348); //ParametroSistema
defined('ID_PARAMETRO_CONFIGURACION_COMPRA')       OR define('ID_PARAMETRO_CONFIGURACION_COMPRA',15); //GRUPO