<?php

$config['const_sisem_licencia']=array();

defined('LICENCIA_PERPETUA_PRUEBA') OR define('LICENCIA_PERPETUA_PRUEBA',config_item("LICENCIA_PERPETUA_PRUEBA"));
defined('LICENCIA_EMPRESA_ID') OR define('LICENCIA_EMPRESA_ID',config_item("LICENCIA_EMPRESA_ID"));
defined('LICENCIA_EMPRESA_RUC') OR define('LICENCIA_EMPRESA_RUC',config_item("LICENCIA_EMPRESA_RUC"));
defined('LICENCIA_CANTIDAD_USUARIO') OR define('LICENCIA_CANTIDAD_USUARIO',config_item("LICENCIA_CANTIDAD_USUARIO"));
defined('LICENCIA_VENTA_FECHA_PERPETUA') OR define('LICENCIA_VENTA_FECHA_PERPETUA',config_item("LICENCIA_VENTA_FECHA_PERPETUA"));
defined('USUARIO_OSE') OR define('USUARIO_OSE',config_item("LICENCIA_EMPRESA_RUC").USUARIO_SOL);

if(LICENCIA_PERPETUA_PRUEBA == 0) {
  //defined('LICENCIA_CANTIDAD_USUARIO') OR define('LICENCIA_CANTIDAD_USUARIO',config_item("LICENCIA_CANTIDAD_USUARIO"));
  //defined('LICENCIA_VENTA_FECHA_PERPETUA') OR define('LICENCIA_VENTA_FECHA_PERPETUA',config_item("LICENCIA_VENTA_FECHA_PERPETUA"));
}
else {
  //defined('LICENCIA_CANTIDAD_USUARIO') OR define('LICENCIA_CANTIDAD_USUARIO',1);
  //defined('LICENCIA_VENTA_FECHA_PERPETUA') OR define('LICENCIA_VENTA_FECHA_PERPETUA',0);
  defined('LICENCIA_VENTA_FECHA_EMISION_MINIMO') OR define('LICENCIA_VENTA_FECHA_EMISION_MINIMO','2018-08-01');
  defined('LICENCIA_VENTA_FECHA_EMISION_MAXIMO') OR define('LICENCIA_VENTA_FECHA_EMISION_MAXIMO','2018-12-31');
}
