<?php
//defined('BASEPATH') OR exit('No direct script access allowed');
$config['const_sisem_catalogo']=array();

//Constantes de Ruta de Carpetas
defined('ID_ATRIBUTO_MERCADERIA')       OR define('ID_ATRIBUTO_MERCADERIA',3); //GRUPO
defined('ID_URL_CARPETA_IMAGENES_CLIENTE')       OR define('ID_URL_CARPETA_IMAGENES_CLIENTE',43); //ParametroSistema
defined('ID_URL_CARPETA_IMAGENES_EMPLEADO')       OR define('ID_URL_CARPETA_IMAGENES_EMPLEADO',44); //ParametroSistema
defined('ID_URL_CARPETA_IMAGENES_PROVEEDOR')       OR define('ID_URL_CARPETA_IMAGENES_PROVEEDOR',45); //ParametroSistema
defined('ID_URL_CARPETA_IMAGENES_SERVICIO')       OR define('ID_URL_CARPETA_IMAGENES_SERVICIO',46); //ParametroSistema

//Constantes de Reportes de Catalogo
defined('NOMBRE_ARCHIVO_REPORTE_LISTACLIENTES')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTACLIENTES',138); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTACLIENTES')       OR define('NOMBRE_ARCHIVO_JASPER_LISTACLIENTES',136); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_MERCADERIAS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_MERCADERIAS',174); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_MERCADERIAS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_MERCADERIAS',173); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_ACTIVOS_FIJOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_ACTIVOS_FIJOS',221); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_ACTIVOS_FIJOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_ACTIVOS_FIJOS',220); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_GASTOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_GASTOS',223); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_GASTOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_GASTOS',222); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_EMPLEADOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_EMPLEADOS',242); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_EMPLEADOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_EMPLEADOS',241); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_PROVEEDORES')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_PROVEEDORES',244); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_PROVEEDORES')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_PROVEEDORES',243); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_COSTOS_AGREGADOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_COSTOS_AGREGADOS',246); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_COSTOS_AGREGADOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_COSTOS_AGREGADOS',245); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_OTRAS_VENTAS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_OTRAS_VENTAS',248); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_OTRAS_VENTAS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_OTRAS_VENTAS',247); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_FAMILIAS_SUBFAMILIAS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_FAMILIAS_SUBFAMILIAS',250); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_FAMILIAS_SUBFAMILIAS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_FAMILIAS_SUBFAMILIAS',249); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_MARCAS_MODELOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_MARCAS_MODELOS',252); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_LISTA_MARCAS_MODELOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_MARCAS_MODELOS',251); //ParametroSistema

//Constantes de Paginacion
defined('ID_NUM_POR_PAGINA_ACTIVOFIJO')       OR define('ID_NUM_POR_PAGINA_ACTIVOFIJO',16);
defined('ID_NUM_POR_RANGO_PAGINA_ACTIVOFIJO')       OR define('ID_NUM_POR_RANGO_PAGINA_ACTIVOFIJO',19);
defined('ID_NUM_POR_PAGINA_GASTO')       OR define('ID_NUM_POR_PAGINA_GASTO',17);
defined('ID_NUM_POR_PAGINA_MERCADERIA')       OR define('ID_NUM_POR_PAGINA_MERCADERIA',6);
defined('ID_NUM_POR_PAGINA_OTRAUNIDADMEDIDA')       OR define('ID_NUM_POR_PAGINA_OTRAUNIDADMEDIDA',93);
defined('ID_NUM_POR_RANGO_PAGINA_MERCADERIA')       OR define('ID_NUM_POR_RANGO_PAGINA_MERCADERIA',18);
defined('ID_NUM_POR_PAGINA_CLIENTE')       OR define('ID_NUM_POR_PAGINA_CLIENTE',10);
defined('ID_NUM_POR_PAGINA_PROVEEDOR')       OR define('ID_NUM_POR_PAGINA_PROVEEDOR',11);
defined('ID_NUM_POR_PAGINA_EMPLEADO')       OR define('ID_NUM_POR_PAGINA_EMPLEADO',12);
defined('ID_NUM_POR_PAGINA_SERVICIO')       OR define('ID_NUM_POR_PAGINA_SERVICIO',15);
defined('ID_TIPO_SERVICIO_SERVICIO')       OR define('ID_TIPO_SERVICIO_SERVICIO',9);


defined('ID_CODIGO_AUTOMATICO_MERCADERIA')       OR define('ID_CODIGO_AUTOMATICO_MERCADERIA',2); //ParametroSistema
defined('ID_CANTIDAD_CODIGO_MERCADERIA')       OR define('ID_CANTIDAD_CODIGO_MERCADERIA',132); //ParametroSistema

defined('ID_LINK_DE_BUSQUEDA')       OR define('ID_LINK_DE_BUSQUEDA',4); //GRUPO
defined('ID_URL_CARPETA_IMAGENES')       OR define('ID_URL_CARPETA_IMAGENES',34); //ParametroSistema
defined('CLIENTE_NO_ESPECIFICADO') OR define('CLIENTE_NO_ESPECIFICADO',0);

defined('ID_ORIGEN_MERCADERIA_GENERAL') OR define('ID_ORIGEN_MERCADERIA_GENERAL',1);
defined('ID_ORIGEN_MERCADERIA_DUA') OR define('ID_ORIGEN_MERCADERIA_DUA',2);
defined('ID_ORIGEN_MERCADERIA_ZOFRA') OR define('ID_ORIGEN_MERCADERIA_ZOFRA',3);

defined('LINEA_PRODUCTO') OR define('LINEA_PRODUCTO',0);
defined('ID_CLIENTES_VARIOS') OR define('ID_CLIENTES_VARIOS',1);
defined('ID_GRUPO_PARAMTRO_VISTA_CLIENTE') OR define('ID_GRUPO_PARAMTRO_VISTA_CLIENTE',14);

defined('ID_TIPO_DOCUMENTO_IDENTIDAD_RUC') OR define('ID_TIPO_DOCUMENTO_IDENTIDAD_RUC',4);
defined('CODIGO_DOCUMENTO_IDENTIDAD_RUC') OR define('CODIGO_DOCUMENTO_IDENTIDAD_RUC',6);
defined('ID_TIPO_DOCUMENTO_IDENTIDAD_SIN_DOC') OR define('ID_TIPO_DOCUMENTO_IDENTIDAD_SIN_DOC',7);
defined('ID_TIPO_DOCUMENTO_IDENTIDAD_OTROS') OR define('ID_TIPO_DOCUMENTO_IDENTIDAD_OTROS',1);

defined('ID_PARAMETRO_AFILIACION_TARJETA_SIETE') OR define('ID_PARAMETRO_AFILIACION_TARJETA_SIETE',288);
defined('ID_PARAMETRO_RESTAURANTE') OR define('ID_PARAMETRO_RESTAURANTE',294);
defined('ID_PARAMETRO_BONIFICACION') OR define('ID_PARAMETRO_BONIFICACION',319);

defined('ID_PARAMETRO_RUBRO_LUBRICANTE') OR define('ID_PARAMETRO_RUBRO_LUBRICANTE',334);
defined('ID_PARAMETRO_RUBRO_REPUESTO') OR define('ID_PARAMETRO_RUBRO_REPUESTO',336);
defined('TIPO_DESCUENTO_PORCENTUAL') OR define('TIPO_DESCUENTO_PORCENTUAL',"0");
defined('TIPO_DESCUENTO_MONTO') OR define('TIPO_DESCUENTO_MONTO',"1");
defined('ID_RADIO_TAXI_NO_ESPECIFICADO') OR define('ID_RADIO_TAXI_NO_ESPECIFICADO',0);
defined('ID_PARAMETRO_CODIGO_BARRA_AUTOMATICO') OR define('ID_PARAMETRO_CODIGO_BARRA_AUTOMATICO',339);
defined('LONGITUD_MAXIMA_CODIGO_AUTOMATICO_MERCADERIA') OR define('LONGITUD_MAXIMA_CODIGO_AUTOMATICO_MERCADERIA',7);
defined('ID_PARAMETRO_DIRECCION_CLIENTE') OR define('ID_PARAMETRO_DIRECCION_CLIENTE',238);

defined('ESTADO_SIN_CAMBIOS_DIRECCION_CLIENTE') OR define('ESTADO_SIN_CAMBIOS_DIRECCION_CLIENTE',0);
defined('ESTADO_INSERTADO_DIRECCION_CLIENTE') OR define('ESTADO_INSERTADO_DIRECCION_CLIENTE',1);
defined('ESTADO_ACTUALIZADO_DIRECCION_CLIENTE') OR define('ESTADO_ACTUALIZADO_DIRECCION_CLIENTE',2);
defined('ESTADO_BORRADO_DIRECCION_CLIENTE') OR define('ESTADO_BORRADO_DIRECCION_CLIENTE',3);
defined('ESTADO_CASILLERO_DISPONIBLE') OR define('ESTADO_CASILLERO_DISPONIBLE',1);
defined('ESTADO_CASILLERO_OCUPADO') OR define('ESTADO_CASILLERO_OCUPADO',0);
defined('ID_PARAMETRO_MODIFICAR_UNIDAD_MEDIDA') OR define('ID_PARAMETRO_MODIFICAR_UNIDAD_MEDIDA',366);
