<?php
$config['const_sisem_ventas']=array();

defined('ID_NUM_POR_PAGINA_COMPROBANTEVENTA')       OR define('ID_NUM_POR_PAGINA_COMPROBANTEVENTA',77);
defined('ID_ATRIBUTO_COMPROBANTE_VENTA')       OR define('ID_ATRIBUTO_COMPROBANTE_VENTA',5); //GRUPO

defined('NOMBRE_ARCHIVO_REPORTE_DETALLADO')       OR define('NOMBRE_ARCHIVO_REPORTE_DETALLADO',72); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_DETALLADO')       OR define('NOMBRE_ARCHIVO_JASPER_DETALLADO',74); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_RESUMIDO')       OR define('NOMBRE_ARCHIVO_REPORTE_RESUMIDO',78); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_RESUMIDO')       OR define('NOMBRE_ARCHIVO_JASPER_RESUMIDO',79); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_PRODUCTO_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_REPORTE_PRODUCTO_MAS_VENDIDO',80); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_PRODUCTO_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_JASPER_PRODUCTO_MAS_VENDIDO',81); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_FAMILIA_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_REPORTE_FAMILIA_MAS_VENDIDO',82); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_FAMILIA_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_JASPER_FAMILIA_MAS_VENDIDO',83); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_VENTA_DIARIA')       OR define('NOMBRE_ARCHIVO_REPORTE_VENTA_DIARIA',84); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_VENTA_DIARIA')       OR define('NOMBRE_ARCHIVO_JASPER_VENTA_DIARIA',85); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_VENTAS_POR_VENDEDOR')       OR define('NOMBRE_ARCHIVO_REPORTE_VENTAS_POR_VENDEDOR',86); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_VENTAS_POR_VENDEDOR')       OR define('NOMBRE_ARCHIVO_JASPER_VENTAS_POR_VENDEDOR',87); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_VENTAS_MENSUALES')       OR define('NOMBRE_ARCHIVO_REPORTE_VENTAS_MENSUALES',91); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_VENTAS_MENSUALES')       OR define('NOMBRE_ARCHIVO_JASPER_VENTAS_MENSUALES',92); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_VENTAS_POR_MERCADERIA')       OR define('NOMBRE_ARCHIVO_REPORTE_VENTAS_POR_MERCADERIAS',141); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_VENTAS_POR_MERCADERIA')       OR define('NOMBRE_ARCHIVO_JASPER_VENTAS_POR_MERCADERIA',140); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_PRODUCTO')       OR define('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_PRODUCTO',170); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO')       OR define('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO',169); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO_PRECIO_VENTA')       OR define('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO_PRECIO_VENTA',206); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO_PRECIO_COMPRA')       OR define('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRODUCTO_PRECIO_COMPRA',240); //ParametroSistema
defined('ID_GANANCIA_PRODUCTO_PRECIO_VENTA')       OR define('ID_GANANCIA_PRODUCTO_PRECIO_VENTA',205); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_PRECIO_BASE_PRODUCTO')       OR define('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_PRECIO_BASE_PRODUCTO',196); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRECIO_BASE_PRODUCTO')       OR define('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_PRECIO_BASE_PRODUCTO',195); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_VENDEDOR')       OR define('NOMBRE_ARCHIVO_REPORTE_GANANCIA_POR_VENDEDOR',178); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_VENDEDOR')       OR define('NOMBRE_ARCHIVO_JASPER_GANANCIA_POR_VENDEDOR',177); //ParametroSistema

defined('NOMBRE_ARCHIVO_REPORTE_SALDO_CLIENTE')       OR define('NOMBRE_ARCHIVO_REPORTE_SALDO_CLIENTE',210); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_SALDO_CLIENTE')       OR define('NOMBRE_ARCHIVO_JASPER_SALDO_CLIENTE',209); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_REGISTRO_VENTA')       OR define('NOMBRE_ARCHIVO_REPORTE_REGISTRO_VENTA',254); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_REGISTRO_VENTA')       OR define('NOMBRE_ARCHIVO_JASPER_REGISTRO_VENTA',253); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_RESUMEN_VENTAS')       OR define('NOMBRE_ARCHIVO_JASPER_RESUMEN_VENTAS',295); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_RESUMEN_VENTAS')       OR define('NOMBRE_ARCHIVO_REPORTE_RESUMEN_VENTAS',296); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_CLIENTES_POR_ZONA')       OR define('NOMBRE_ARCHIVO_JASPER_CLIENTES_POR_ZONA',316); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_CLIENTES_POR_ZONA')       OR define('NOMBRE_ARCHIVO_REPORTE_CLIENTES_POR_ZONA',317); //ParametroSistema

defined('NOMBRE_PLANTILLA_EXCEL_BOLETA_MASIVA')       OR define('NOMBRE_PLANTILLA_EXCEL_BOLETA_MASIVA',139); //ParametroSistema

defined('ID_PARAMETRO_CONFIGURACION_VENTA')       OR define('ID_PARAMETRO_CONFIGURACION_VENTA',12); //GRUPO

defined('ID_NOMBRE_JASPER_FORMATO_ZOFRA_A4') OR define('ID_NOMBRE_JASPER_FORMATO_ZOFRA_A4',152);
defined('ID_NOMBRE_JASPER_FORMATO_A4') OR define('ID_NOMBRE_JASPER_FORMATO_A4',154);

defined('ID_NOMBRE_JASPER_FORMATO_TICKET_ZOFRA') OR define('ID_NOMBRE_JASPER_FORMATO_TICKET_ZOFRA',156);
defined('ID_NOMBRE_JASPER_FORMATO_TICKET') OR define('ID_NOMBRE_JASPER_FORMATO_TICKET',158);
//nobres de jasper
defined('NOMBRE_BOLETA_FISICO') OR define('NOMBRE_BOLETA_FISICO','Venta/BoletaFisico.jasper');
defined('NOMBRE_BOLETA_ELECTRONICO') OR define('NOMBRE_BOLETA_ELECTRONICO','Venta/Ticket/DocumetoElectronicoTicket5.7.jasper');//BoletaElectronico.jasper
defined('NOMBRE_FACTURA_FISICO') OR define('NOMBRE_FACTURA_FISICO','Venta/FacturaFisico.jasper');
defined('NOMBRE_FACTURA_ELECTRONICO') OR define('NOMBRE_FACTURA_ELECTRONICO','Venta/Ticket/DocumetoElectronicoTicket5.7.jasper');
defined('NOMBRE_RECIBO_ORDEN_PEDIDO') OR define('NOMBRE_RECIBO_ORDEN_PEDIDO','Venta/OrdenPedido.jasper');
defined('NOMBRE_BOLETA_ELECTRONICO_TIPO_T') OR define('NOMBRE_BOLETA_ELECTRONICO_TIPO_T','Venta/Ticket/Zofra/DocumentoElectronicoZofra8.0_TipoT.jasper');
defined('NOMBRE_BOLETA_ELECTRONICO_TIPO_Z') OR define('NOMBRE_BOLETA_ELECTRONICO_TIPO_Z','Venta/Ticket/Zofra/DocumentoElectronicoZofra8.0_TipoZ.jasper');

defined('NOMBRE_BOLETA_ELECTRONICO_TIPO_T_A4') OR define('NOMBRE_BOLETA_ELECTRONICO_TIPO_T_A4','Venta/A4/DocumentoElectronicoZofraA4_TipoT.jasper');
defined('NOMBRE_BOLETA_ELECTRONICO_TIPO_Z_A4') OR define('NOMBRE_BOLETA_ELECTRONICO_TIPO_Z_A4','Venta/A4/DocumentoElectronicoZofraA4_TipoZ.jasper');
defined('NOMBRE_DOCUMENTO_ELECTRONICO_A4') OR define('NOMBRE_DOCUMENTO_ELECTRONICO_A4','Venta/A4/DocumentoElectronicoA4.jasper');

//PARA IMPRESION
defined('NOMBRE_COMANDA_DETALLE_ANULADO') OR define('NOMBRE_COMANDA_DETALLE_ANULADO','Venta/Ticket/ComandaItemEliminado.jasper');

defined('NOMBRE_REPORTE_VERIFICACION_CORRELATIVIDAD') OR define('NOMBRE_REPORTE_VERIFICACION_CORRELATIVIDAD','ListadoCorrelativosDisponibles/ListadoCorrelativosDisponibles');

defined('ID_MOTIVO_NOTA_SALIDA_VENTA_CON_DOCUMENTO') OR define('ID_MOTIVO_NOTA_SALIDA_VENTA_CON_DOCUMENTO',1);
defined('ID_MOTIVO_NOTA_SALIDA_DEVOLUCION_AL_PROVEEDOR') OR define('ID_MOTIVO_NOTA_SALIDA_DEVOLUCION_AL_PROVEEDOR',25);
defined('ID_MOTIVO_NOTA_ENTRADA_COMPRA_CON_DOCUMENTO') OR define('ID_MOTIVO_NOTA_ENTRADA_COMPRA_CON_DOCUMENTO',2);
defined('ID_MOTIVO_NOTA_ENTRADA_DEVOLUCION_CLIENTE_CON_DOCUMENTO') OR define('ID_MOTIVO_NOTA_ENTRADA_DEVOLUCION_CLIENTE_CON_DOCUMENTO',24);
defined('NUMERO_DECIMALES_VENTA') or define('NUMERO_DECIMALES_VENTA',2);
defined('NUMERO_DECIMALES_VALOR_UNITARIO_VENTA') or define('NUMERO_DECIMALES_VALOR_UNITARIO_VENTA',10);

defined('CODIGO_SERIE_FACTURA') or define('CODIGO_SERIE_FACTURA','F');
defined('CODIGO_SERIE_BOLETA') or define('CODIGO_SERIE_BOLETA','B');
defined('CODIGO_TIPO_DOCUMENTO_BOLETA') or define('CODIGO_TIPO_DOCUMENTO_BOLETA','03');

defined('CODIGO_ESTADO_EMITIDO') or define('CODIGO_ESTADO_EMITIDO',1);
defined('CODIGO_ESTADO_MODIFICADO') or define('CODIGO_ESTADO_MODIFICADO',2);
defined('CODIGO_ESTADO_ANULADO') or define('CODIGO_ESTADO_ANULADO',3);

defined('TIPO_VENTA_MERCADERIA') OR define('TIPO_VENTA_MERCADERIA',1);
defined('TIPO_VENTA_SERVICIOS') OR define('TIPO_VENTA_SERVICIOS',2);
defined('TIPO_VENTA_ACTIVO_FIJO') OR define('TIPO_VENTA_ACTIVO_FIJO',3);
defined('TIPO_VENTA_OTRAS_VENTAS') OR define('TIPO_VENTA_OTRAS_VENTAS',4);
defined('FILTRO_TODOS') OR define('FILTRO_TODOS', "%");
defined('PORCENTAJE_IGV') OR define('PORCENTAJE_IGV', 18.00);

defined('ID_PARAMETRO_VISTA_VENTA') OR define('ID_PARAMETRO_VISTA_VENTA', 233);
defined('PARAMETRO_ID_MONEDA_BOLETA_ZOFRA') OR define('PARAMETRO_ID_MONEDA_BOLETA_ZOFRA', 255);

defined('RUTA_CONFIG_IMPRESION') OR define('RUTA_CONFIG_IMPRESION', DIR_ROOT_ASSETS_CLIENTE."\data\impresion\config.json");
defined('RUTA_CARPETA_CONFIG_IMPRESION') OR define('RUTA_CARPETA_CONFIG_IMPRESION', DIR_ROOT_ASSETS_CLIENTE."\data\impresion\\");
defined('RUTA_CONFIG_CORRELATIVO') OR define('RUTA_CONFIG_CORRELATIVO', DIR_ROOT_ASSETS_CLIENTE."\data\correlativodocumento\config.json");
defined('INDICADOR_FORMATO_OTRO') OR define('INDICADOR_FORMATO_OTRO', 0);
defined('INDICADOR_FORMATO_FACTURA_ELECTRONICA_VENTA') OR define('INDICADOR_FORMATO_FACTURA_ELECTRONICA_VENTA', 2);
defined('INDICADOR_FORMATO_FACTURA_FISICA_VENTA') OR define('INDICADOR_FORMATO_FACTURA_FISICA_VENTA', 20);
defined('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA') OR define('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA', 4);
defined('INDICADOR_FORMATO_BOLETA_FISICA_VENTA') OR define('INDICADOR_FORMATO_BOLETA_FISICA_VENTA', 40);
defined('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA_T') OR define('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA_T', 41);
defined('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA_Z') OR define('INDICADOR_FORMATO_BOLETA_ELECTRONICA_VENTA_Z', 42);
defined('INDICADOR_FORMATO_NOTA_CREDITO') OR define('INDICADOR_FORMATO_NOTA_CREDITO', 8);
defined('INDICADOR_FORMATO_NOTA_DEBITO') OR define('INDICADOR_FORMATO_NOTA_DEBITO', 9);
defined('INDICADOR_FORMATO_ORDEN_PEDIDO') OR define('INDICADOR_FORMATO_ORDEN_PEDIDO', 78);
defined('INDICADOR_FORMATO_COMANDA') OR define('INDICADOR_FORMATO_COMANDA', 86);
defined('INDICADOR_FORMATO_GUIA_REMISION') OR define('INDICADOR_FORMATO_GUIA_REMISION', 10);
defined('INDICADOR_FORMATO_CODIGO_BARRAS') OR define('INDICADOR_FORMATO_CODIGO_BARRAS', 93);

defined('PARAMETRO_COSTO_O_PRECIO_PROMEDIO') OR define('PARAMETRO_COSTO_O_PRECIO_PROMEDIO', 262);

defined('PARAMETRO_LISTA_PRECIO_AVANZADO') OR define('PARAMETRO_LISTA_PRECIO_AVANZADO', 266);

defined('ID_PARAMETRO_GUARDAR_CLIENTE_VENTA') OR define('ID_PARAMETRO_GUARDAR_CLIENTE_VENTA', 272);
defined('ID_PARAMETRO_GUARDAR_PRODUCTO_VENTA') OR define('ID_PARAMETRO_GUARDAR_PRODUCTO_VENTA', 273);

defined('ID_PARAMETRO_CALCULAR_CANTIDAD') OR define('ID_PARAMETRO_CALCULAR_CANTIDAD', 282);
defined('ID_PARAMETRO_CLIENTE_SIN_RUC') OR define('ID_PARAMETRO_CLIENTE_SIN_RUC', 285);
defined('ID_PARAMETRO_COMPROBANTE_AUTOMATICO') OR define('ID_PARAMETRO_COMPROBANTE_AUTOMATICO', 286);
defined('ID_PARAMETRO_MAX_COMPROBANTE_AUTOMATICO') OR define('ID_PARAMETRO_MAX_COMPROBANTE_AUTOMATICO', 287);
defined('ID_PARAMETRO_CANTIDAD_COMPROBANTE_LIBRE_SERIE') OR define('ID_PARAMETRO_CANTIDAD_COMPROBANTE_LIBRE_SERIE', 291);
defined('ID_PARAMETRO_PORCENTAJE_POR_FACTURA') OR define('ID_PARAMETRO_PORCENTAJE_POR_FACTURA', 293);

//PARA RESTAURANTE
defined('ESTADO_PRE_CUENTA_PENDIENTE') OR define('ESTADO_PRE_CUENTA_PENDIENTE', '0');
defined('ESTADO_PRE_CUENTA_CANJEADO') OR define('ESTADO_PRE_CUENTA_CANJEADO', '1');
defined('ESTADO_CANJEADO_PENDIENTE') OR define('ESTADO_CANJEADO_PENDIENTE', '0');
defined('ESTADO_CANJEADO_PARCIAL') OR define('ESTADO_CANJEADO_PARCIAL', '1');
defined('ESTADO_CANJEADO_TOTAL') OR define('ESTADO_CANJEADO_TOTAL', '2');

defined('SITUACION_MESA_DISPONIBLE') OR define('SITUACION_MESA_DISPONIBLE', 'D');
defined('SITUACION_MESA_OCUPADO') OR define('SITUACION_MESA_OCUPADO', 'O');
defined('ESTADO_IMPRESION_ENVIADO') OR define('ESTADO_IMPRESION_ENVIADO', '1');
defined('ESTADO_IMPRESION_PENDIENTE') OR define('ESTADO_IMPRESION_PENDIENTE', '0');

defined('INDICADOR_IMPRESION_CONSUMO') OR define('INDICADOR_IMPRESION_CONSUMO', '0');
defined('INDICADOR_IMPRESION_DETALLADO') OR define('INDICADOR_IMPRESION_DETALLADO', '1');
defined('RUTA_JASPER_CONSUMO_FACTURA') OR define('RUTA_JASPER_CONSUMO_FACTURA', 'Venta/Ticket/DocumetoElectronicoTicket5.7.jasper');
defined('RUTA_JASPER_CONSUMO_BOLETA') OR define('RUTA_JASPER_CONSUMO_BOLETA', 'Venta/Ticket/DocumetoElectronicoTicket5.7.jasper');
defined('NOMBRE_ARCHIVO_REPORTE_MARCA_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_REPORTE_MARCA_MAS_VENDIDO',284); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_MARCA_MAS_VENDIDO')       OR define('NOMBRE_ARCHIVO_JASPER_MARCA_MAS_VENDIDO',283); //ParametroSistema

defined('ID_PARAMETRO_HORA_REPORTE') OR define('ID_PARAMETRO_HORA_REPORTE', 308);
defined('ID_PARAMETRO_ORDEN_PEDIDO_DUA') OR define('ID_PARAMETRO_ORDEN_PEDIDO_DUA', 312);
defined('ID_PARAMETRO_CALCULO_IGV_DESDE_TOTAL') OR define('ID_PARAMETRO_CALCULO_IGV_DESDE_TOTAL', 313);
defined('ID_PARAMETRO_FACTURACION_ELECTRONICA') OR define('ID_PARAMETRO_FACTURACION_ELECTRONICA', 314);
defined('ID_PARAMETRO_ZONA')       OR define('ID_PARAMETRO_ZONA',315);
defined('ID_PARAMETRO_NUMERO_DIAS_EXPIRACION_CERTIFICADO') OR define('ID_PARAMETRO_NUMERO_DIAS_EXPIRACION_CERTIFICADO', 318);
defined('ID_PARAMETRO_PROFORMA') OR define('ID_PARAMETRO_PROFORMA', 338);

defined('ID_PARAMETRO_MODALIDAD_TRASLADO_PUBLICO')       OR define('ID_PARAMETRO_MODALIDAD_TRASLADO_PUBLICO',"1");
defined('ID_PARAMETRO_MOTIVO_TRASLADO_VENTA')       OR define('ID_PARAMETRO_MOTIVO_TRASLADO_VENTA',1);
defined('ID_PARAMETRO_RUBRO_TRANSPORTE') OR define('ID_PARAMETRO_RUBRO_TRANSPORTE',335);
defined('ID_PARAMETRO_RUBRO_CLINICA') OR define('ID_PARAMETRO_RUBRO_CLINICA',337);
defined('ID_PARAMETRO_FORMA_CALCULO_VENTA') OR define('ID_PARAMETRO_FORMA_CALCULO_VENTA',340);
defined('ID_PARAMETRO_OBSERVACION_GUIA') OR define('ID_PARAMETRO_OBSERVACION_GUIA',341);
defined('ID_PARAMETRO_TIPO_CAMBIO_BUSQUEDA_AVANZADA_PRODUCTO') OR define('ID_PARAMETRO_TIPO_CAMBIO_BUSQUEDA_AVANZADA_PRODUCTO',342);
defined('ID_PARAMETRO_MARGEN_UTILIDAD_BUSQUEDA_AVANZADA_PRODUCTO') OR define('ID_PARAMETRO_MARGEN_UTILIDAD_BUSQUEDA_AVANZADA_PRODUCTO',343);
defined('ID_PARAMETRO_COMISION_META_VENTA_PRODUCTO') OR define('ID_PARAMETRO_COMISION_META_VENTA_PRODUCTO',354);
defined('ID_PARAMETRO_NUMERO_MAXIMO_CLIENTES_RANKING_CLIENTES_MAYORES_VENTAS') OR define('ID_PARAMETRO_NUMERO_MAXIMO_CLIENTES_RANKING_CLIENTES_MAYORES_VENTAS',357);

defined('NOMBRE_ARCHIVO_JASPER_LISTA_PRECIOS')       OR define('NOMBRE_ARCHIVO_JASPER_LISTA_PRECIOS',330); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_LISTA_PRECIOS')       OR define('NOMBRE_ARCHIVO_REPORTE_LISTA_PRECIOS',331); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_REMUNERACION_EMPLEADOS_META_MENSUAL')       OR define('NOMBRE_ARCHIVO_JASPER_REMUNERACION_EMPLEADOS_META_MENSUAL',332); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_REMUNERACION_EMPLEADOS_META_MENSUAL')       OR define('NOMBRE_ARCHIVO_REPORTE_REMUNERACION_EMPLEADOS_META_MENSUAL',333); //ParametroSistema
defined('NOMBRE_ARCHIVO_REPORTE_VENTA_GENERAL_LUBRICANTE')       OR define('NOMBRE_ARCHIVO_REPORTE_VENTA_GENERAL_LUBRICANTE',352); //ParametroSistema
defined('NOMBRE_ARCHIVO_JASPER_VENTA_GENERAL_LUBRICANTE')       OR define('NOMBRE_ARCHIVO_JASPER_VENTA_GENERAL_LUBRICANTE',353); //ParametroSistema

defined('ID_PARAMETRO_SELECCION_UNA_PROFORMA') OR define('ID_PARAMETRO_SELECCION_UNA_PROFORMA', 362);
defined('ID_PARAMETRO_APLICA_PRECIO_ESPECIAL') OR define('ID_PARAMETRO_APLICA_PRECIO_ESPECIAL',363);
defined('ID_TIPO_PRECIO_UNITARIO_INCLUIDO_IGV') OR define('ID_TIPO_PRECIO_UNITARIO_INCLUIDO_IGV',1);
defined('INDICADOR_NO_OPERACION_GRATUITA') OR define('INDICADOR_NO_OPERACION_GRATUITA',0);
defined('CODIGO_CATEGORIA_DESCUENTO') OR define('CODIGO_CATEGORIA_DESCUENTO',1);
defined('ID_PARAMETRO_APLICA_ORDEN_CORRELATIVIDAD') OR define('ID_PARAMETRO_APLICA_ORDEN_CORRELATIVIDAD',364);
defined('ID_PARAMETRO_CALCULOLO_PRECIO_SOLES_DOLARES') OR define('ID_PARAMETRO_CALCULOLO_PRECIO_SOLES_DOLARES',365);